# Generated by Django 4.2.26 on 2025-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
